config/routes.rb
OscNew::Application.routes.draw do

  root :to => "contrats#index"
  
  resources :accounts
  
  resources :budgetaire_references do
    member do
      get :ask_delete
    end
  end
    
  resources :contrats do
    member do
      get :ask_delete
      get :show_not_authorized_users
      get :show_not_authorized_groups
      get :reporting
      post :add_user
      post :add_group
      post :delete_user
      post :delete_group
      post :duplicate
    end
    collection do
      get :my_last_search
      get :search
    end
    resources :todolists do
      member do
        post :update_positions
        get :ask_delete
      end
      resources :todoitems do
        member do
          post :undone
          post :done
          post :update_positions
          get :ask_delete
        end
      end
    end
    resources :signatures do
      member do
        get :ask_delete
      end    
    end
    resources :soumissions do
      member do
        get :ask_delete
        get :getpdf
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :refus do
      member do
        get :ask_delete
      end
    end
    resources :notifications do
      member do
        get :ask_delete
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :clotures do
      member do
        get :ask_delete
      end
    end
    resources :echeanciers do
      member do
        get :ask_delete
      end
    end
    resources :contrat_files do
      member do
        get :edit_description
        put :update_description
        get :ask_delete
      end
      collection do
        post :sort_by
      end
    end
    resources :descriptifs do
      member do
        get :ask_delete
      end
    end
  end
  
  resources :contrat_types do
    member do
      get :ask_delete
    end
  end
  resources :departements do
    member do
      get :ask_delete
    end
  end
  resources :departement_subscriptions do
    member do
      post :create
    end
  end
  resources :groups do
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  
  resources :key_words do
    member do
      get :ask_delete
    end
   
    collection do
      post :sort_by
    end
  end
  
  resources :laboratoires do
    member do
      get :ask_delete
    end
  end
  resources :laboratoire_subscriptions do
    member do
      post :create
    end
  end
  resources :lignes do
    collection do
      get :search
      get :search_in_create
      get :my_last_search
      post :toggle_show_justification_data_preferences
    end
    member do
      get :ask_delete
      get :ask_desactivate
      get :bilan
      post :desactivate
      post :activate
    end
    resources :versements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_fonctionnements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_equipements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_missions do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_salaires do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
      collection do
        post :search_people_from_ose
        post :search_people_from_gef
        get :create_salaires_from_gef
      end
    end
    resources :depense_non_ventilees do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_communs do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
  end

  resources :memberships

  resources :organisme_gestionnaires do
    member do
      get :ask_delete
    end
    resources :organisme_gestionnaires_tauxes
  end

  resources :projets do
    member do
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  resources  :rubrique_comptables do
    member do
      get :ask_delete
    end
  end
  resources :sous_contrats do
    member do
      get :ask_delete
    end
  end
  resources :tutelles do 
    member do
      get :ask_delete
    end
  end
  resources :tutelle_logos
  resources :tutelle_subscriptions do
    member do
      post :create
    end
  end

  resources :users do
    collection do 
      get :search_by_name
    end
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    resources :user_images
  end
  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/projet.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
class Projet < ActiveRecord::Base
  acts_as_authorizable

  has_many :laboratoire_subscriptions, :dependent => :destroy
  has_many :laboratoires, :through => :laboratoire_subscriptions, :order => "nom"
  
  has_many :departement_subscriptions, :dependent => :destroy
  has_many :departements, :through => :departement_subscriptions, :order => "nom"
  
  has_many :tutelle_subscriptions, :dependent => :destroy
  has_many :tutelles, :through => :tutelle_subscriptions, :order => "nom"
  
  has_many :sous_contrats, :as => :entite
  has_many :roles , :as => :authorizable 
    
  validates_presence_of :nom, :message => " doît être obligatoirement rempli"
  validates_uniqueness_of :nom, :message => " est déjà utilisé par un autre projet"
  validates_presence_of :date_debut, :message => " doît être obligatoirement rempli"
  validates_presence_of :date_fin, :message => " doît être obligatoirement rempli"
  validate :date_fin_cannot_be_greater_than_date_debut
  
  def date_fin_cannot_be_greater_than_date_debut
      if self.date_debut > self.date_fin
        errors.add(:date_fin, " : la date de fin doit être supérieure à la date de début")
      end
  end
  
  def self.find_all_team_for(user)
    user_equipes_querry = ["SELECT p.id FROM projets p 
                           INNER JOIN roles AS r ON r.authorizable_type = 'Projet' and r.authorizable_id = p.id
                           INNER JOIN roles_users AS ru ON ru.role_id = r.id 
                           WHERE ru.user_id = ?",user.id]
                           
    mes_equipes = Projet.find_by_sql(user_equipes_querry)
    
    group_equipes_querry = ["SELECT p.id FROM projets p 
                            INNER JOIN roles AS r ON r.authorizable_type = 'Projet' and r.authorizable_id = p.id
                            INNER JOIN group_rights  as gr ON gr.role_id = r.id
                            INNER JOIN memberships AS m ON m.group_id = gr.group_id
                            WHERE m.user_id = ?",user.id]
    mes_equipes_from_group = Projet.find_by_sql(group_equipes_querry)
    mes_equipes = mes_equipes | mes_equipes_from_group
    
    return mes_equipes
  end
  
  def is_in_laboratoire? labo
    is_in = 0
    for laboratoire in self.laboratoires
      if laboratoire.id == labo.id
        is_in = is_in + 1
      end
    end
    for departement in self.departements
      if departement.laboratoire.id == labo.id
        is_in = is_in + 1
      end
    end
    if is_in == 0
      return false
    else
      return true
    end 
  end
  
  def is_in_tutelle? tutel
    is_in = 0
    for tutelle in self.tutelles
      if tutelle.id == tutel.id
        is_in = is_in + 1
      end
    end
    if is_in == 0
      return false
    else
      return true
    end 
  end
  
  def type
    return self.class
  end
end

app/controllers/projets_controller.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
class ProjetsController < ApplicationController
  
  def search_by_name
    
    @admin = false
    if current_user.is_admin?
      @admin = true
    end
    @admin_fonc = false
    if current_user.is_fonc_admin?
      @admin_fonc = true
    end
    
    count = Projet.find(:all, :conditions => ["nom LIKE ?", "%#{params[:query]}%"]).size    
    @projets = Projet.paginate(:order => 'nom',
                          :per_page => 10,
                          :page => params[:page]||1,
                          :conditions => ["nom LIKE ?", "%#{params[:query]}%"])
        
    respond_to do |format|
      format.js { 
                  render :update do |page|
                    page.replace_html  'list', :partial => 'list'
                    if params[:query] != ''
                      page.replace_html 'ajax_result', ""+count.to_s+" projet(s) trouvé(s)"
                    else
                      page.replace_html 'ajax_result',""+count.to_s+" projets référencés"
                    end
                  end
                }
    end
  end
  
  
  
  # GET /projets
  # GET /projets.xml
  def index
    #@projets = Projet.find(:all, :order =>'nom')
    
        
    @count = Projet.find(:all, :conditions => ["nom LIKE ?", "%#{params[:query]}%"]).size    

    @projets = Projet.paginate(:order => 'nom',
                          :per_page => 10,
                          :page => params[:page]||1,
                          :conditions => ["nom LIKE ?", "%#{params[:query]}%"])
    
    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @projets.to_xml }
    end
  end

  # GET /projets/1
  # GET /projets/1.xml
  def show
    @projet = Projet.find(params[:id])
    @laboratoires = @projet.laboratoires
    @tutelles = @projet.tutelles
    
    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @projet.to_xml }
    end
  end

  # GET /projets/new
  def new
    @projet = Projet.new
    @non_modifiable = []
  end

  # GET /projets/1;edit
  def edit
    @projet = Projet.find(params[:id])
    
    @non_modifiable = []
    if (@projet.verrou == 'SI INRIA') and @projet.verrou_listchamps
      verrou_listchamps_tableau = @projet.verrou_listchamps.split(';')
      for champ in verrou_listchamps_tableau do
        @non_modifiable << champ
      end
    end
    
    @laboratoire_subscriptions = @projet.laboratoire_subscriptions.find(:all, :include => [:laboratoire], :order => "laboratoires.nom")
    @laboratoires = Laboratoire.find(:all, :order => "nom")
    
    @departements = Departement.find(:all, :order => "nom")
    @departement_subscriptions = @projet.departement_subscriptions
    
    @tutelle_subscriptions = @projet.tutelle_subscriptions.find(:all, :include => [:tutelle], :order => "tutelles.nom")
    @tutelles = @projet.tutelles.find(:all, :order => "nom")
    @tutelles_restantes = Tutelle.find(:all, :order => "nom") - @tutelles
  end

  # POST /projets
  # POST /projets.xml
  def create
    @projet = Projet.new(clean_date_params(params[:projet]))
    
    respond_to do |format|
      if @projet.save
        flash[:notice] = "L'équipe a bien été créée."
        format.html { redirect_to projet_url(@projet) }
        format.xml  { head :created, :location => projet_url(@projet) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @projet.errors.to_xml }
      end
    end
  end

  # PUT /projets/1
  # PUT /projets/1.xml
  def update
    @projet = Projet.find(params[:id])
    # en cas d'erreur ...
    @laboratoire_subscriptions = @projet.laboratoire_subscriptions.find(:all, :include => [:laboratoire], :order => "laboratoires.nom")
    @laboratoires = Laboratoire.find(:all, :order => "nom")
    @tutelle_subscriptions = @projet.tutelle_subscriptions.find(:all, :include => [:tutelle], :order => "tutelles.nom")
    @tutelles = @projet.tutelles.find(:all, :order => "nom")
    @tutelles_restantes = Tutelle.find(:all, :order => "nom") - @tutelles
    @non_modifiable = []
    respond_to do |format|
      if @projet.update_attributes(clean_date_params(params[:projet]))
        for sous_contrat in @projet.sous_contrats do
          if sous_contrat.ligne
            sous_contrat.ligne.update_nom        
          end
        end
        
        flash[:notice] = "L'équipe a bien été modifiée."
        format.html { redirect_to projet_url(@projet) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @projet.errors.to_xml }
      end
    end
  end

  def ask_delete
    @projet = Projet.find(params[:id])
    respond_to do |format|
      format.html 
    end
  end

  # DELETE /projets/1
  # DELETE /projets/1.xml
  def destroy
    @projet = Projet.find(params[:id])
    if @projet.sous_contrats.size == 0
      flash[:notice] = 'L\'équipe '+@projet.nom+' a été supprimée.'
      roles = Role.find( :all, 
                       :conditions => [ 'authorizable_type = ? and authorizable_id = ?', 
                                         "Projet", @projet.id ] )
      #suppression des droits associes
      for role in roles
        group_rights = GroupRight.find( :all,:conditions => [ 'role_id = ?',role.id] )
        for group_right in group_rights
          group_right.destroy
        end
        users_with_role = User.find(:all, :include => :roles,:conditions => ["roles.id = ?",role.id])

        for user_with_role in users_with_role
          user_with_role.roles.delete( role )
        end
        role.destroy
      end

      @projet.destroy
    else
      flash[:notice] = 'Cette équipe ne peut pas être supprimée car des contrats lui sont liés'
    end
    respond_to do |format|
      format.html { redirect_to projets_url }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projets_helper.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
module ProjetsHelper
end

app/views/projets/_add_departement_subscription.html.erb
<% if (@projet.departement_subscriptions.empty?) && (@projet.laboratoire_subscriptions.empty?) %>
  <p class="comment">Vous pouvez associer l'équipe <%= @projet.nom %> à un département à l'aide du formulaire ci-dessous.</p>
  <%= form_for(:projet, :url => "/departement_subscriptions/create?projet_id="+@projet.id.to_s,:remote => true, :html => {:class => 'inline',:method => :post }) do |f| %>  
    <label for="departement_subscription_departement_id">Associer le dépt. </label>
    <%= select "departement_subscription", "departement_id", @departements.collect {|t| [ t.nom, t.id ] } %>
    à l'équipe <%= @projet.nom %>
    <%= submit_tag "Valider" %>
  <% end %>
<% end %>

<% if (!@projet.laboratoire_subscriptions.empty?) %>
<p class="comment">Association impossible car le projet est déjà rattaché à un laboratoire.</p>
<% end %>

app/views/projets/_list.html.erb
<div class="pagination">
  <%= will_paginate @projets, :previous_label => "&nbsp;&laquo;&nbsp;",
                              :next_label => "&nbsp;&raquo;&nbsp;",
                              :renderer => "PaginationLinkRenderer",
                              :remote => {:with =>"'query='+escape($F('query'))"}%>
</div>

<% for projet in @projets %>
	<% if projet.date_fin < Date.today %>
		<div class="box_1_per_line <%= cycle("even","odd") %> archive" id="p_<%= projet.id %>" >
	<% else %>
		<div class="box_1_per_line <%= cycle("even","odd") %>" id="p_<%= projet.id %>">
	<% end %>
	<div class="infos">
		<div class="primary"><%= link_to projet.nom, projet_path(projet) %></div>
		<div class="secondary"><%=h truncate(projet.description,:length => 90, :ommission =>"...") %></div>
	</div>
	<div class="actions">
		<%= link_to 'Editer', edit_projet_path(projet) %>
		<%= link_to_remote_redbox "Supprimer",
        { :url => ask_delete_projet_path(projet), 
          :method => :get}, 
        { :title => "Supprimer ce projet" } %>
			
	</div>
	<div style="clear:both;"></div>
</div>
<% end %>

app/views/projets/_list_departement_subscriptions.html.erb
<% if !@departement_subscriptions.empty? %>
<% for departement_subscription in @departement_subscriptions %>
<div class="small_infos_actions" id="departement_subscription_<%= departement_subscription.id %>">
	<div class="infos">
		<div class="name">
			<%= link_to departement_subscription.departement.nom, departement_path(departement_subscription.departement) %>
			(<%= link_to departement_subscription.departement.laboratoire.nom, laboratoire_path(departement_subscription.departement.laboratoire) %>)
		</div>
		<div class="description"><%=h truncate(departement_subscription.departement.description,:length =>80,:ommission =>"...") %></div>
	</div>
	<div class="actions">
		<%= link_to_remote "",{ :url => departement_subscription_path(departement_subscription),  :method => :delete } , :class => 'delete'%>			
	</div>
	<div style="clear:both;"></div>
</div>
<% end %>
<% end %>

app/views/projets/_list_laboratoire_subscriptions.html.erb
<% if !@laboratoire_subscriptions.empty? %>
<% for laboratoire_subscription in @laboratoire_subscriptions %>
<div class="small_infos_actions" id="laboratoire_subscription_<%= laboratoire_subscription.id %>">
		<div class="infos">
			<div class="name"><%= link_to laboratoire_subscription.laboratoire.nom, laboratoire_path(laboratoire_subscription.laboratoire) %></div>
			<div class="description"><%=h truncate(laboratoire_subscription.laboratoire.description,:length =>80,:ommission =>"...") %></div>
		</div>
		<div class="actions">
			<%= link_to_remote "",{ :url => laboratoire_subscription_path(laboratoire_subscription),  :method => :delete } , :class => 'delete'%>			
		</div>
		<div style="clear:both;"></div>
	</div>
<% end %>
<% end %>

app/views/projets/_list_tutelle_subscriptions.html.erb
<% if @tutelle_subscriptions.empty? %>
<% else %>
<% for tutelle_subscription in @tutelle_subscriptions %>
<div class="small_photo_infos_actions <%= cycle('one', 'two') %>"  id="tutelle_subscription_<%= tutelle_subscription.id %>">
		<div class="photo">
			<%= show_tutelle_logo_small tutelle_subscription.tutelle.tutelle_logo %>
		</div>	
		<div class="infos">
			<div class="name"><%= link_to tutelle_subscription.tutelle.nom, tutelle_path(tutelle_subscription.tutelle) %></div>
			<div class="description"><%=h tutelle_subscription.tutelle.description %></div>
		</div>
		<div class="actions">
			<%= link_to_remote "", { :url => tutelle_subscription_path(tutelle_subscription),  :method => :delete }, :class => 'delete' %>			
		</div>
		<div style="clear:both;"></div>
	</div>
<% end %>
<% end %>

app/views/projets/ask_delete.html.erb
<div class="content">
	<p>
	Etes-vous certain de vouloir supprimer l'équipe <strong>"<%= @projet.nom %>"</strong> ?
	</p>
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= link_to "Oui", projet_path(@projet), :method => :delete %>
	<div style="clear:both;"></div>
</div>

app/views/projets/edit.html.erb
<% if @projet.date_fin < Date.today %>
<div class="archive">
<% end %>

<%= error_messages_for @projet %>


<div class='section'>
	<h2><strong>Descriptif</strong> de l'équipe</h2>
<%= form_for(:projet, :url => projet_path(@projet), :html => { :method => :put }) do |f| %>
<fieldset>
	
	
<p>
	<label for="projet_nom" class="required">Nom</label><br />
	<% if @non_modifiable.include?('nom') %>
	  <strong><%= @projet.nom %></strong>
	<% else %>
	  <%= f.text_field :nom %>
	<% end %>
</p>
<p>
	<label for="projet_description">Description</label><br />
	<% if @non_modifiable.include?('description') %>
	  <strong><%= @projet.description %></strong>
	<% else %>
	  <%= f.text_area :description %>
	<% end %>
</p>
<p class="date_select">
	<label for="projet_date_debut">Date de début du projet</label><br />
	 <% if @non_modifiable.include?('date_debut') %>
	   <strong><%= @projet.date_debut %></strong>
	 <% else %>
	   <%= f.date_select("date_debut", 
						:order => [:day, :month, :year],
						:start_year => 1980,
						:use_month_numbers => true) %>
	 <% end %>
</p>
<p class="date_select">
	<label for="projet_date_fin">Date de fin du projet</label><br />
	<% if @non_modifiable.include?('date_fin') %>
	   <strong><%= @projet.date_fin %></strong>
	 <% else %>
	
		<% if @projet.date_fin.to_s == "2099-12-31" %>
		<span id="non_connue">
		  <span style="margin-left:15px;">Date infinie</span>
		  <span><a href="" onclick="disableDateNonConnue(); return false;" id="normal_date">Annuler</a></span>
		  <input type='text' name='projet[date_fin]' id="projet_date_fin_infinite" value="2099-12-31" style="display:none" />
		</span>
		<span id="disable_non_connue" style="display:none;">
		  <span id="dateFin">
			<%= f.date_select("date_fin", 
								:order => [:day, :month, :year], 
								:start_year => @projet.date_debut.year, 
								:use_month_numbers => true) %>
		  </span>
		  <span><a href="" onclick="enableDateNonConnue(); return false;" id="infinite_date">Date infinie</a></span>
		</span>
		<script>
			$('projet_date_fin_3i').disable();
			$('projet_date_fin_2i').disable();
			$('projet_date_fin_1i').disable();
		</script>
		<% else %>
		<span id="non_connue"  style="display:none;">
		  <span style="margin-left:15px;">Date infinie</span><br />
		  <span class="aide"><a href="" onclick="disableDateNonConnue(); return false;" id="normal_date">Annuler</a></span>
		  <input type='text' name='projet[date_fin]' id="projet_date_fin_infinite" value="2099-12-31" style="display:none" />
		</span>
		<span id="disable_non_connue">
		  <span id="dateFin">
			<%= f.date_select("date_fin", 
								:order => [:day, :month, :year], 
								:start_year => @projet.date_debut.year, 
								:use_month_numbers => true) %>
		  </span><br />
		  <span class="aide"><a href="" onclick="enableDateNonConnue(); return false;" id="infinite_date">Date infinie</a></span>
		</span>
		<script>
			$('projet_date_fin_infinite').disable();
		</script>
		<% end %>
	  <% end %>
</p>
</fieldset>
<p class="submit">
	<%= submit_tag "Mettre à jour" %>
</p>

<script>
function disableDateNonConnue(){
	$("disable_non_connue").show();
	$("non_connue").hide();
	$('projet_date_fin_3i').enable();
	$('projet_date_fin_2i').enable();
	$('projet_date_fin_1i').enable();
	$('projet_date_fin_infinite').disable();
}
function enableDateNonConnue(){
	$("disable_non_connue").hide();
	$("non_connue").show();
	$('projet_date_fin_3i').disable();
	$('projet_date_fin_2i').disable();
	$('projet_date_fin_1i').disable();
	$('projet_date_fin_infinite').enable();
}
</script>

<% end %>
</div>

<div class='section'>
	<h2>Association à un <strong>laboratoire</strong></h2>
	<div id="projetEditLaboratoires">
		<%= render :partial => "list_laboratoire_subscriptions" %>	
	</div>
	<div id="add_laboratoire_subscription">
		<% if @projet.laboratoire_subscriptions.empty? %>
		<%= render :partial => 'add_laboratoire_subscription' %>
		<% end %>
	</div>
	<br />
</div>

<div class='section'>
	<h2>Association à un <strong>laboratoire</strong> via un <strong>département</strong></h2>
	<div id="projetEditDepartements">
	<%= render :partial => 'list_departement_subscriptions' %>
	</div>
	<div id="add_departement_subscription">
	<%= render :partial => 'add_departement_subscription' %>
	</div>
	<br />
</div>


<div class='section'>
	<h2>Associations à des <strong>tutelles</strong></h2>
	<div id="projetEditTutelles">
		<%= render :partial => "list_tutelle_subscriptions" %>	
	</div>
	
	<div id="add_tutelle_subscription">
		<%= render :partial => 'add_tutelle_subscription' %>
	</div>
	<br />
</div>

<% if @projet.date_fin < Date.today %>
</div>
<% end %>

app/views/projets/index.html.erb
<div id='list'>
<%=  render :partial => "list" %>	
</div>
<script type="text/javascript" language="javascript">
  function updateResult(page_number){

    new Ajax.Request('/projets/search_by_name?page='+page_number,
      {asynchronous:true, evalScripts:true, method:'get',
      parameters:'query='+escape($F('query'))
                      });
    }
  </script>

app/views/projets/new.html.erb
<%= error_messages_for @projet %>

<%= form_for(:projet, :url => projets_path) do |f| %>
<fieldset>
  <p>
    <label for="projet_nom" class="required">Nom</label><br />
    <%= f.text_field :nom %>
  </p>
  <p>
    <label for="projet_description">Description</label><br />
    <%= f.text_area :description %>
  </p>
  <p class="date_select">
	<label for="projet_date_debut">Date de début du projet</label><br />
	 <%= f.date_select("date_debut", 
						:order => [:day, :month, :year],
						:start_year => 1980,
						:use_month_numbers => true) %>
  </p>
  <p class="date_select">
	<label for="projet_date_fin">Date de fin du projet</label><br />
	<span id="non_connue"  style="display:none;">
	  <span style="margin-left:15px;">Date infinie</span><br />
	  <span class="aide"><a href="" onclick="disableDateNonConnue(); return false;" id="normal_date">Annuler</a></span>
	  <input type='text' name='projet[date_fin]' id="projet_date_fin_infinite" value="2099-12-31" style="display:none" />
	</span>
	<span id="disable_non_connue">
	  <span id="dateFin">
		<%= f.date_select("date_fin", 
							:order => [:day, :month, :year], 
							:start_year => 1980, 
							:use_month_numbers => true) %>
	  </span><br />
	  <span class="aide"><a href="" onclick="enableDateNonConnue(); return false;" id="infinite_date">Date infinie</a></span>
	</span>
	<script>
		$('projet_date_fin_infinite').disable();
	</script>

	<script>
	function disableDateNonConnue(){
		$("disable_non_connue").show();
		$("non_connue").hide();
		$('projet_date_fin_3i').enable();
		$('projet_date_fin_2i').enable();
		$('projet_date_fin_1i').enable();
		$('projet_date_fin_infinite').disable();
	}
	function enableDateNonConnue(){
		$("disable_non_connue").hide();
		$("non_connue").show();
		$('projet_date_fin_3i').disable();
		$('projet_date_fin_2i').disable();
		$('projet_date_fin_1i').disable();
		$('projet_date_fin_infinite').enable();
	}
	</script>

  </p>
</fieldset>
  <p class="submit">
    <%= submit_tag "Créer l'équipe" %> ou <%= link_to "Annuler", projets_path %>
  </p>
<% end %>

app/views/projets/show.html.erb
<% if @projet.date_fin < Date.today %>
<div class="archive">
<% end %>

<div class="section">
	<% if @projet.departements.size != 0 %>
	<h2>Association à un <strong>laboratoire</strong></h2>
		<% for departement in @projet.departements %>
		<div class="list_infos">
			<div class="name"><%= link_to departement.laboratoire.nom, laboratoire_path(departement.laboratoire) %> via le département  <%= link_to departement.nom, departement_path(departement) %></div>
			<div class="description"><%=h departement.laboratoire.description %></div>
		</div>
		<% end %>
	<% end %>

	<% if @laboratoires.size != 0 %> 
	<h2>Association à un <strong>laboratoire</strong></h2>
		<% for laboratoire in @laboratoires %>
		<div class="list_infos">
			<div class="name"><%= link_to laboratoire.nom, laboratoire_path(laboratoire) %></div>
			<div class="description"><%=h laboratoire.description %></div>
		</div>
		<% end %>
		<% end %>

		<% if (@projet.departements.size == 0) && (@laboratoires.size == 0) %>
		<h2><strong>Aucune</strong> association à un <strong>laboratoire</strong></h2>
		<% end %>
</div>

<div class="section">
	<h2>Associations à des <strong>tutelles</strong></h2>
	<% for tutelle in @tutelles %>
	<div class="small_photo_infos">
		<div class="photo">
			<%= show_tutelle_logo_small tutelle.tutelle_logo %>
		</div>
		<div class="infos">
			<div class="name"><%= link_to tutelle.nom, tutelle_path(tutelle) %></div>
			<div class="description"><%=h tutelle.description %></div>
		</div>
		<div style="clear:left;"></div>
	</div>
	<% end %>
</div>
<% if @projet.date_fin < Date.today %>
</div>
<% end %>