config/routes.rb
OscNew::Application.routes.draw do

  root :to => "contrats#index"
  
  resources :accounts
  
  resources :budgetaire_references do
    member do
      get :ask_delete
    end
  end
    
  resources :contrats do
    member do
      get :ask_delete
      get :show_not_authorized_users
      get :show_not_authorized_groups
      get :reporting
      post :add_user
      post :add_group
      post :delete_user
      post :delete_group
      post :duplicate
    end
    collection do
      get :my_last_search
      get :search
    end
    resources :todolists do
      member do
        post :update_positions
        get :ask_delete
      end
      resources :todoitems do
        member do
          post :undone
          post :done
          post :update_positions
          get :ask_delete
        end
      end
    end
    resources :signatures do
      member do
        get :ask_delete
      end    
    end
    resources :soumissions do
      member do
        get :ask_delete
        get :getpdf
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :refus do
      member do
        get :ask_delete
      end
    end
    resources :notifications do
      member do
        get :ask_delete
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :clotures do
      member do
        get :ask_delete
      end
    end
    resources :echeanciers do
      member do
        get :ask_delete
      end
    end
    resources :contrat_files do
      member do
        get :edit_description
        put :update_description
        get :ask_delete
      end
      collection do
        post :sort_by
      end
    end
    resources :descriptifs do
      member do
        get :ask_delete
      end
    end
  end
  
  resources :contrat_types do
    member do
      get :ask_delete
    end
  end
  resources :departements do
    member do
      get :ask_delete
    end
  end
  resources :departement_subscriptions do
    member do
      post :create
    end
  end
  resources :groups do
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  
  resources :key_words do
    member do
      get :ask_delete
    end
   
    collection do
      post :sort_by
    end
  end
  
  resources :laboratoires do
    member do
      get :ask_delete
    end
  end
  resources :laboratoire_subscriptions do
    member do
      post :create
    end
  end
  resources :lignes do
    collection do
      get :search
      get :search_in_create
      get :my_last_search
      post :toggle_show_justification_data_preferences
    end
    member do
      get :ask_delete
      get :ask_desactivate
      get :bilan
      post :desactivate
      post :activate
    end
    resources :versements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_fonctionnements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_equipements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_missions do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_salaires do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
      collection do
        post :search_people_from_ose
        post :search_people_from_gef
        get :create_salaires_from_gef
      end
    end
    resources :depense_non_ventilees do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_communs do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
  end

  resources :memberships

  resources :organisme_gestionnaires do
    member do
      get :ask_delete
    end
    resources :organisme_gestionnaires_tauxes
  end

  resources :projets do
    member do
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  resources  :rubrique_comptables do
    member do
      get :ask_delete
    end
  end
  resources :sous_contrats do
    member do
      get :ask_delete
    end
  end
  resources :tutelles do 
    member do
      get :ask_delete
    end
  end
  resources :tutelle_logos
  resources :tutelle_subscriptions do
    member do
      post :create
    end
  end

  resources :users do
    collection do 
      get :search_by_name
    end
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    resources :user_images
  end
  

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/notifications_controller.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
class NotificationsController < ApplicationController  
  before_filter :is_my_research_in_session?
  
  include UIEnhancements::SubList
  helper :SubList

  auto_complete_for :notification, :etablissement_rattachement_porteur
  auto_complete_for :notification, :etablissement_gestionnaire_du_coordinateur
  auto_complete_for :notification, :organisme_financeur
  auto_complete_for :notification, :organisme_payeur
  auto_complete_for :notification, :etablissement_gestionnaire
  auto_complete_for :notification, :poles_competivites

  sub_list 'NotificationFrancePartenaires', 'notification' do |new_notification_france_partenaire|
  end
  sub_list 'NotificationEuropePartenaires', 'notification' do |new_notification_europe_partenaire|
  end
  sub_list 'NotificationPartenaires', 'notification' do |new_notification_partenaire|
  end
  sub_list 'NotificationPersonnels', 'notification' do |new_notification_personnel|
  end
  sub_list 'SousContratNotification', 'notification' do |new_sous_contrat_notification|
  end
  sub_list 'Avenant', 'notification' do |avenant|
  end

  def update_type_contrat
    @contrat = Contrat.find(params[:contrat_id])
    @contrat_type = ContratType.find(params[:type])

    respond_to do |format|
      format.js {
        render :inline => "<%= display_contrat_type(@contrat_type) %>"
      }
    end
  end


  # GET /notifications
  # GET /notifications.xml
  def index
    @notifications = Notification.find(:all)

    respond_to do |format|
      format.html # index.rhtml
    end
  end

  # GET /notifications/1
  # GET /notifications/1.xml
  def show
    @contrats = Contrat.find(:all, :order => "acronyme")
    @contrat = Contrat.find(params[:contrat_id])
    @notification = @contrat.notification

    respond_to do |format|
      format.html {
        if !@contrat.is_consultable? current_user
          flash[:error] = ("Vos droits dans l'application ne vous permettent pas d'accéder au contrat "+@contrat.acronyme+".").html_safe()  
          redirect_to contrats_path
        end
      }
      format.pdf do
         pdf = PrawnPdfDrawer.new(@notification, request)
         send_data pdf.render, :filename => 'notification_'+@contrat.acronyme+'.pdf', :type => 'application/pdf', :disposition => 'inline'
      end
    end
  end

  # GET /notifications/new
  def new
    @contrats = Contrat.find(:all, :order => "acronyme")
    @contrat = Contrat.find(params[:contrat_id])
    @key_words = KeyWord.find(:all)
    @soumission = @contrat.soumission    
    #@sous_contrats = @contrat.sous_contrats

    error = false
    if !@contrat.is_editable? current_user 
      flash[:error] = ("Vos droits dans l'application ne vous permettent pas de créer une notification pour le contrat "+@contrat.acronyme+".").html_safe()       
      redirect_to contrat_path(@contrat)
      error = true
    else
      if !@contrat.notification.nil?
        flash[:error] = ("Il est impossible de créer une notification pour le contrat "+@contrat.acronyme+" car elle existe déja.").html_safe()       
        redirect_to contrat_notification_path(@contrat, @contrat.notification)
        error = true
      else
        if @contrat.soumission.nil? 
          flash[:error] = ("Il est impossible de créer une notification pour le contrat "+@contrat.acronyme+" car la 
          soumission n'est pas enregistrée. Merci de procéder à la création de la soumission.").html_safe()       
          redirect_to new_contrat_soumission_path(@contrat)
          error = true
        else
          if @contrat.signature.nil?
            flash[:error] = ("Il est impossible de créer une notification pour le contrat "+@contrat.acronyme+" car la signature 
            n'est pas enregistrée. Merci de procéder à la création de la signature.").html_safe()       
            redirect_to new_contrat_signature_path(@contrat)
            error = true
          end
          if !@contrat.refu.nil?
            flash[:error] = ("Il est impossible de créer une notification pour le contrat "+@contrat.acronyme+" car un refus à déjà été enregistré.").html_safe()       
            redirect_to contrat_refu_path(@contrat, @contrat.refu)
            error = true
          end
        end
      end
    end

    if !error
      @notification = Notification.new
      @non_modifiables = @notification.get_non_modifiables
      # Pré-chargement des infos de la soumission
      ## Généralités
      @notification.contrat_type_id = @soumission.contrat_type_id
      @notification.nombre_mois = @soumission.nombre_mois
      @notification.etablissement_gestionnaire = @soumission.etablissement_gestionnaire
      @notification.organisme_gestionnaire_id = @soumission.organisme_gestionnaire_id
      @notification.organisme_financeur = @soumission.organisme_financeur
      @notification.porteur = @soumission.porteur
      @notification.etablissement_rattachement_porteur = @soumission.etablissement_rattachement_porteur
      @notification.est_porteur = @soumission.est_porteur
      @notification.coordinateur = @soumission.coordinateur
      @notification.etablissement_gestionnaire_du_coordinateur = @soumission.etablissement_gestionnaire_du_coordinateur

      ## Mots clés et thématiques
      @notification.key_words = @soumission.key_words
      @notification.mots_cles_libres = @soumission.mots_cles_libres
      @notification.thematiques = @soumission.thematiques
      @notification.poles_competivites = @soumission.poles_competivites

      ## Partenaires
      #--- Pré-chargement des partenaires en France
      for partenaire in @soumission.soumission_france_partenaires
        a = @notification.notification_france_partenaires.build(
        :etablissement_gestionnaire => partenaire.etablissement_gestionnaire,
        :ville => partenaire.ville,
        :nom => partenaire.nom)
        # Assignation d'un identifiant
        a.id = Time.now.to_i+rand(1000000000000000).to_i
      end

      #--- Pré-chargement des partenaires en Europe
      for partenaire in @soumission.soumission_europe_partenaires
        a = @notification.notification_europe_partenaires.build(
        :etablissement_gestionnaire => partenaire.etablissement_gestionnaire,
        :ville => partenaire.ville,
        :nom => partenaire.nom,
        :pays => partenaire.pays)
        # Assignation d'un identifiant
        a.id = Time.now.to_i+rand(1000000000000000).to_i        
      end

      #--- Pré-chargement des partenaires hors Europe
      for partenaire in @soumission.soumission_partenaires
        a = @notification.notification_partenaires.build(
        :etablissement_gestionnaire => partenaire.etablissement_gestionnaire,
        :ville => partenaire.ville,
        :nom => partenaire.nom,
        :pays => partenaire.pays)
        # Assignation d'un identifiant
        a.id = Time.now.to_i+rand(1000000000000000).to_i        
      end

      ## Moyens accordés
      @notification.ma_type_montant = @soumission.md_type_montant
      @notification.ma_fonctionnement = @soumission.md_fonctionnement
      @notification.ma_equipement = @soumission.md_equipement
      @notification.ma_salaire = @soumission.md_salaire
      @notification.ma_mission = @soumission.md_mission
      @notification.ma_couts_indirects = @soumission.md_couts_indirects
      @notification.ma_frais_gestion_mutualises_local = 0.00
      @notification.ma_frais_gestion_mutualises = 0.00
      @notification.ma_allocation = @soumission.md_allocation
      @notification.ma_total = @soumission.md_total

      for sous_contrat in @contrat.sous_contrats
        a = @notification.sous_contrat_notifications.build(:sous_contrat_id => sous_contrat.id)
        a.id = Time.now.to_i+rand(1000000000000000).to_i        
      end


      ## Personnel accordé
      @notification.pa_doctorant = @soumission.pd_doctorant
      @notification.pa_post_doc = @soumission.pd_post_doc
      @notification.pa_ingenieur = @soumission.pd_ingenieur
      @notification.pa_autre = @soumission.pd_autre
      @notification.pa_equivalent_temps_plein = @soumission.pd_equivalent_temps_plein

      #--- Pré-chargement du personnel impliqué
      for personnel in @soumission.soumission_personnels
        a = @notification.notification_personnels.build(
        :nom => personnel.nom,
        :prenom => personnel.prenom,
        :statut => personnel.statut,
        :tutelle => personnel.tutelle,
        :pourcentage => personnel.pourcentage)
        # Assignation d'un identifiant
        a.id = Time.now.to_i+rand(1000000000000000).to_i        
      end


    end

  end

  # GET /notifications/1;edit
  def edit
    @contrats = Contrat.find(:all, :order => "acronyme")
    @contrat = Contrat.find(params[:contrat_id])
    @notification = @contrat.notification
    @non_modifiables = @notification.get_non_modifiables

    if !@contrat.is_editable? current_user 
      flash[:error] = ("Vos droits dans l'application ne vous permettent pas d'éditer la notification du contrat "+@contrat.acronyme+".").html_safe()       
      redirect_to contrat_notification_path(@contrat)
    end

    for sous_contrat in @contrat.sous_contrats
      if @notification.sous_contrat_notifications.find(:all, :conditions => ["sous_contrat_id = ?", sous_contrat.id]).size != 1
        a = @notification.sous_contrat_notifications.build(:sous_contrat_id => sous_contrat.id)
        a.id = Time.now.to_i+rand(1000000000000000).to_i
      end
    end

  end

  # POST /notifications
  # POST /notifications.xml
  def create
    params[:notification] = clean_date_params(params[:notification])
    @contrats = Contrat.find(:all, :order => "acronyme")
    @contrat = Contrat.find(params[:contrat_id])    

    params[:notification][:key_word_ids] ||= []

    @notification = Notification.new(params[:notification])
    @notification.contrat = @contrat
    @non_modifiables = @notification.get_non_modifiables
    success = true

app/helpers/notifications_helper.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
module NotificationsHelper
  
  def my_notification_error_messages_for notification
    txt =""
    if notification && !notification.errors.empty?
  	  txt = "<div class='errorExplanation' id='errorExplanation'>"
  	  txt += "<h2>"+notification.errors.size.to_s+" erreur(s) de saisie empêche(nt) l'enregistrement de la notification du contrat</h2>"
      txt += "<ul>"
      notification.errors.each do |attr, msg| 
  	    if attr.to_s =="notification_partenaires" 
  			  txt += "<li><strong>Partenaires hors Europe</strong> : le champ <strong>nom</strong> est un champ obligatoire, merci de le renseigner</li>"
  		  elsif attr.to_s =="notification_europe_partenaires"
  			  txt += "<li><strong>Partenaires en Europe</strong> : le champ <strong>nom</strong> est un champ obligatoire, merci de le renseigner</li>"
  		  elsif attr.to_s =="notification_france_partenaires" 
  			  txt += "<li><strong>Partenaires en France</strong> : le champ <strong>nom</strong> est un champ obligatoire, merci de le renseigner</li>"
  		  elsif attr.to_s =="notification_personnels" 
  			  txt += "<li><strong>Personnel impliqué</strong> : tous les champs sont obligatoires, merci de les renseigner</li>"
  		  elsif attr.to_s =="avenants" 
  			  txt += "<li><strong>Avenant</strong> : tous les champs sont obligatoires et les dates doivent être valides, merci de les renseigner</li>"
  		  else 
  			  txt += "<li>"+msg+"</li>"
  		  end
      end
      txt += "</ul>"
      txt += "</div>"
    end
    return txt.html_safe()
  end
  
  
   def display_contrat_type(element)
     ret = ""
     if !element.parent.nil?
      ret += display_contrat_type(element.parent)+" > "
      ret += element.nom 
     else
      ret += element.nom
     end
     ret.html_safe()
   end
  
  
end

app/views/notifications/_ask_delete_avenant.html.erb
<div class="content">
	<p>
		Etes-vous certain de vouloir supprimer cet avenant ?
	</p>
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= sub_list_accept_to_remove_link("avenant") %>
 	<div style="clear:both;"></div>
</div>

app/views/notifications/_ask_delete_notification_europe_partenaire.html.erb
<div class="content">
	<p>
		Etes-vous certain de vouloir supprimer ce partenaire localisé en Europe ?
	</p>
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= sub_list_accept_to_remove_link("notification_europe_partenaire" ) %>
 	<div style="clear:both;"></div>
</div>

app/views/notifications/_ask_delete_notification_france_partenaire.html.erb
<div class="content">
	<p>
		Etes-vous certain de vouloir supprimer ce partenaire localisé en France ?
	</p>
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= sub_list_accept_to_remove_link("notification_france_partenaire" ) %>
 	<div style="clear:both;"></div>
</div>

app/views/notifications/_ask_delete_notification_personnel.html.erb
<div class="content">
	<p>
		Etes-vous certain de vouloir supprimer ce personnel impliqué dans le contrat ?
	</p>
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= sub_list_accept_to_remove_link("notification_personnel" ) %>
 	<div style="clear:both;"></div>
</div>

app/views/notifications/_avenant.html.erb
<% @avenant = avenant %>
<div id="<%= "avenant_#{avenant.id}" %>" style="border:1px dotted #aaa;padding:10px;margin-bottom:10px">
	<div style="float:right;">
	<% unless controller.action_name == 'show' %>
		<%= sub_list_remove_link avenant, 'avenant' %>
	<% end %>
	</div>
	
	<p class="inline">
		<label class="required">Date de l'avenant</label><br />
		<%= date_select 'avenant[]', 'date',
										:order => [:day, :month, :year],
										:use_month_numbers => true %>
	  
	</p>
	<p>
		<label class="required">Commentaires</label><br />
		<%= text_area 'avenant[]', 'commentaires', :class => "textareafield" %>
	</p>
	
</div>

app/views/notifications/_notification_france_partenaire.html.erb
<% @notification_france_partenaire = notification_france_partenaire %>
<div id="<%= "notification_france_partenaire_#{notification_france_partenaire.id}" %>">
	<p>
		<% @class = '' %>
		<% if !notification_france_partenaire.nom.nil? %>
			<% if notification_france_partenaire.nom.empty?  %>
				<% @class = "blank"  %>
				<% notification_france_partenaire.nom = "Nom" %>
			<% end %>
		<% else %>
			<% @class = "blank"  %>
			<% notification_france_partenaire.nom = "Nom" %>
		<% end %>
		
		<%= text_field 'notification_france_partenaire[]', 'nom',
			{ :class => 'four_cell required '+@class,
				:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Nom' };",
				:onfocus =>"if (this.value == 'Nom') { $(this).removeClassName('blank'); this.value=''; };"
			} %>
		
			<% @class = '' %>			
			<% if !notification_france_partenaire.laboratoire.nil? %>
				<% if notification_france_partenaire.laboratoire.empty?  %>
					<% @class = "blank"  %>
					<% notification_france_partenaire.laboratoire = "Laboratoire" %>
				<% end %>
			<% else %>
				<% @class = "blank"  %>
				<% notification_france_partenaire.laboratoire = "Laboratoire" %>
			<% end %>

			<%= text_field 'notification_france_partenaire[]', 'laboratoire',
				{ :class => 'four_cell '+@class,
					:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Laboratoire' };",
					:onfocus =>"if (this.value == 'Laboratoire') { $(this).removeClassName('blank'); this.value=''; };"
				} %>
		
		<% @class = '' %>			
		<% if !notification_france_partenaire.etablissement_gestionnaire.nil? %>
			<% if notification_france_partenaire.etablissement_gestionnaire.empty?  %>
				<% @class = "blank"  %>
				<% notification_france_partenaire.etablissement_gestionnaire = "Etab. gestionnaire" %>
			<% end %>
		<% else %>
			<% @class = "blank"  %>
			<% notification_france_partenaire.etablissement_gestionnaire = "Etab. gestionnaire" %>
		<% end %>
		
		<%= text_field 'notification_france_partenaire[]', 'etablissement_gestionnaire',
			{ :class => 'four_cell '+@class,
				:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Etab. gestionnaire' };",
				:onfocus =>"if (this.value == 'Etab. gestionnaire') { $(this).removeClassName('blank'); this.value=''; };"
			} %>

		<% @class = '' %>
		<% if !notification_france_partenaire.ville.nil? %>
			<% if notification_france_partenaire.ville.empty?  %>
				<% @class = "blank"  %>
				<% notification_france_partenaire.ville = "Ville" %>
			<% end %>
		<% else %>
			<% @class = "blank"  %>
			<% notification_france_partenaire.ville = "Ville" %>
		<% end %>
		
		<%= text_field 'notification_france_partenaire[]', 'ville',
			{ :class => 'four_cell '+@class,
				:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Ville' };",
				:onfocus =>"if (this.value == 'Ville') { $(this).removeClassName('blank'); this.value=''; };"
			} %>
				
		<input class="four_cell" type="hidden" value="France" id="input_<%= notification_france_partenaire.id %>" />


				
		<% unless controller.action_name == 'show' %>
 			<%= sub_list_remove_link notification_france_partenaire, 'notificationFrancePartenaire' %>
		<% end %>
		</p>
</div>

app/views/notifications/_notification_partenaire.html.erb
<% @notification_partenaire = notification_partenaire %>
<div id="<%= "notification_partenaire_#{notification_partenaire.id}" %>">
	<p>
		<% @class = '' %>
		<% if !notification_partenaire.nom.nil? %>
			<% if notification_partenaire.nom.empty?  %>
				<% @class = "blank"  %>
				<% notification_partenaire.nom = "Nom" %>
			<% end %>
		<% else %>
			<% @class = "blank"  %>
			<% notification_partenaire.nom = "Nom" %>
		<% end %>

		<%= text_field 'notification_partenaire[]', 'nom',
			{ :class => 'four_cell required '+@class,
				:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Nom' };",
				:onfocus =>"if (this.value == 'Nom') { $(this).removeClassName('blank'); this.value=''; };"
			} %>
		
		
		<% @class = '' %>
		<% if !notification_partenaire.etablissement_gestionnaire.nil? %>
			<% if notification_partenaire.etablissement_gestionnaire.empty?  %>
				<% @class = "blank"  %>
				<% notification_partenaire.etablissement_gestionnaire = "Etab. gestionnaire" %>
			<% end %>
		<% else %>
			<% @class = "blank"  %>
			<% notification_partenaire.etablissement_gestionnaire = "Etab. gestionnaire" %>
		<% end %>
		
		<%= text_field 'notification_partenaire[]', 'etablissement_gestionnaire',
			{ :class => 'four_cell '+@class,
				:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Etab. gestionnaire' };",
				:onfocus =>"if (this.value == 'Etab. gestionnaire') { $(this).removeClassName('blank'); this.value=''; };"
				} %>


			<% @class = '' %>
			<% if !notification_partenaire.ville.nil? %>
				<% if notification_partenaire.ville.empty?  %>
					<% @class = "blank"  %>
					<% notification_partenaire.ville = "Ville" %>
				<% end %>
			<% else %>
				<% @class = "blank"  %>
				<% notification_partenaire.ville = "Ville" %>
			<% end %>

			<%= text_field 'notification_partenaire[]', 'ville',
				{ :class => 'four_cell '+@class,
					:value => @value,
					:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Ville' };",
					:onfocus =>"if (this.value == 'Ville') { $(this).removeClassName('blank'); this.value=''; };"
					} %>


		<% @class = '' %>
		<% if !notification_partenaire.pays.nil? %>
			<% if notification_partenaire.pays.empty?  %>
				<% @class = "blank"  %>
				<% notification_partenaire.pays = "Pays" %>
			<% end %>
		<% else %>
			<% @class = "blank"  %>
			<% notification_partenaire.pays = "Pays" %>
		<% end %>

		<%= text_field 'notification_partenaire[]', 'pays',
			{ :class => 'four_cell '+@class,
				:value => @value,
				:onblur => "if (this.value == '') { $(this).addClassName('blank'); this.value='Pays' };",
				:onfocus =>"if (this.value == 'Pays') { $(this).removeClassName('blank'); this.value=''; };"
			} %>

		<% unless controller.action_name == 'show' %>
			<%= sub_list_remove_link notification_partenaire, 'notificationPartenaire' %>
		<% end %>
</p>
</div>

app/views/notifications/ask_delete.html.erb
<div class="content">
	<p>
		Etes-vous certain de vouloir supprimer la notification du contrat <strong> <%= @contrat.long_acronyme %> </strong> ?
	</p>
	Cette suppression entraîne également la suppression de l'échéancier.
	
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= link_to "Oui", contrat_notification_path(@contrat, @notification), :method => :delete %>
	<div style="clear:both;"></div>
</div>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>Contrat</th>
    <th>Contrat type</th>
  </tr>
  
<% for notification in @notifications %>
  <tr>
    <td><%=h notification.contrat_id %></td>
    <td><%=h notification.contrat_type_id %></td>
    <td><%= link_to 'Show', notification_path(notification) %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification_path(notification), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New notification', new_notification_path %>

app/views/notifications/new.html.erb
<h2>Notification de contrat</h2>

<%= my_notification_error_messages_for @notification %>

<%= form_for(:notification, :url => contrat_notifications_path) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f} %>
  <div class="form-box submit" id="submit">
    <%= submit_tag "Créer la notification" %>
    ou
    <%= link_to "Annuler", contrat_path(@contrat) %>
  </div>
<% end %>

<% content_for :right do %>
  <div id="navigation">
    <h2>Aide à la navigation dans le formulaire</h2>
    <ul>
      <li><a href="#indicator">Haut de page</a></li>
      <li><a href="#TypeContrat">Type de contrat</a></li>
      <li><a href="#InformationsGenerales">Informations générales - Porteur et coordinateur - Site Web</a></li>
      <li><a href="#MotsCles">Mots clés et thématiques</a></li>
      <li><a href="#Partenaires">Partenaires</a></li>
      <li><a href="#MoyensAccordes">Moyens accordés</a></li>
      <li><a href="#PersonnelAccorde">Personnel accordé</a></li>
      <li><a href="#PersonnelImplique">Personnel impliqué</a></li>
      <li class="last"><a href="#submit">Création de la notification</a></li>
    </ul>
  </div>
  <script type="text/javascript">
    new App.NavigatorHelper();
  </script>
<% end %>