config/routes.rb
OscNew::Application.routes.draw do

  root :to => "contrats#index"
  
  resources :accounts
  
  resources :budgetaire_references do
    member do
      get :ask_delete
    end
  end
    
  resources :contrats do
    member do
      get :ask_delete
      get :show_not_authorized_users
      get :show_not_authorized_groups
      get :reporting
      post :add_user
      post :add_group
      post :delete_user
      post :delete_group
      post :duplicate
    end
    collection do
      get :my_last_search
      get :search
    end
    resources :todolists do
      member do
        post :update_positions
        get :ask_delete
      end
      resources :todoitems do
        member do
          post :undone
          post :done
          post :update_positions
          get :ask_delete
        end
      end
    end
    resources :signatures do
      member do
        get :ask_delete
      end    
    end
    resources :soumissions do
      member do
        get :ask_delete
        get :getpdf
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :refus do
      member do
        get :ask_delete
      end
    end
    resources :notifications do
      member do
        get :ask_delete
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :clotures do
      member do
        get :ask_delete
      end
    end
    resources :echeanciers do
      member do
        get :ask_delete
      end
    end
    resources :contrat_files do
      member do
        get :edit_description
        put :update_description
        get :ask_delete
      end
      collection do
        post :sort_by
      end
    end
    resources :descriptifs do
      member do
        get :ask_delete
      end
    end
  end
  
  resources :contrat_types do
    member do
      get :ask_delete
    end
  end
  resources :departements do
    member do
      get :ask_delete
    end
  end
  resources :departement_subscriptions do
    member do
      post :create
    end
  end
  resources :groups do
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  
  resources :key_words do
    member do
      get :ask_delete
    end
   
    collection do
      post :sort_by
    end
  end
  
  resources :laboratoires do
    member do
      get :ask_delete
    end
  end
  resources :laboratoire_subscriptions do
    member do
      post :create
    end
  end
  resources :lignes do
    collection do
      get :search
      get :search_in_create
      get :my_last_search
      post :toggle_show_justification_data_preferences
    end
    member do
      get :ask_delete
      get :ask_desactivate
      get :bilan
      post :desactivate
      post :activate
    end
    resources :versements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_fonctionnements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_equipements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_missions do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_salaires do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
      collection do
        post :search_people_from_ose
        post :search_people_from_gef
        get :create_salaires_from_gef
      end
    end
    resources :depense_non_ventilees do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_communs do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
  end

  resources :memberships

  resources :organisme_gestionnaires do
    member do
      get :ask_delete
    end
    resources :organisme_gestionnaires_tauxes
  end

  resources :projets do
    member do
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  resources  :rubrique_comptables do
    member do
      get :ask_delete
    end
  end
  resources :sous_contrats do
    member do
      get :ask_delete
    end
  end
  resources :tutelles do 
    member do
      get :ask_delete
    end
  end
  resources :tutelle_logos
  resources :tutelle_subscriptions do
    member do
      post :create
    end
  end

  resources :users do
    collection do 
      get :search_by_name
    end
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    resources :user_images
  end
  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/tutelle_logo.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
class TutelleLogo < ActiveRecord::Base
  belongs_to :tutelle
  file_column :logo,
              :magick => {
                :geometry => "76x76", :crop => "1:1",
                :versions => { "medium" => "400x400",
                                "small" => "38x38"}
              }
end

app/controllers/tutelle_logos_controller.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
class TutelleLogosController < ApplicationController
  # GET /tutelle_logos
  # GET /tutelle_logos.xml
  def index
    tutelle = Tutelle.find(params[:tutelle_id]) 
    @tutelle_logos = tutelle.tutelle_logos.find(:all)

    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @tutelle_logos.to_xml }
    end
  end

  # GET /tutelle_logos/1
  # GET /tutelle_logos/1.xml
  def show
    @tutelle_logo = TutelleLogo.find(params[:id])
    @tutelle_logo.tutelle = Tutelle.find(params[:tutelle_id]) 

    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @tutelle_logo.to_xml }
    end
  end

  # GET /tutelle_logos/new
  def new
    @tutelle_logo = TutelleLogo.new
    @tutelle_logo.tutelle = Tutelle.find(params[:tutelle_id]) 
  end

  # GET /tutelle_logos/1;edit
  def edit
    @tutelle_logo = TutelleLogo.find(params[:id])
  end

  # POST /tutelle_logos
  # POST /tutelle_logos.xml
  def create
    @tutelle_logo = TutelleLogo.new(params[:tutelle_logo])
    @tutelle_logo.tutelle = Tutelle.find(params[:tutelle_id]) 
    respond_to do |format|
      if @tutelle_logo.save
        flash[:notice] = 'Le logo à été ajouté avec succès.'
        format.html { redirect_to edit_tutelle_path(@tutelle_logo.tutelle) }
        format.xml  { head :created, :location => tutelle_logo_url(@tutelle_logo) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tutelle_logo.errors.to_xml }
      end
    end
  end

  # PUT /tutelle_logos/1
  # PUT /tutelle_logos/1.xml
  def update
    @tutelle_logo = TutelleLogo.find(params[:id])
    @tutelle_logo.tutelle = Tutelle.find(params[:tutelle_id])
    respond_to do |format|
      if @tutelle_logo.update_attributes(params[:tutelle_logo])
        flash[:notice] = "Le logo à été mise à jour avec succès."
        format.html { redirect_to edit_tutelle_path(@tutelle_logo.tutelle) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tutelle_logo.errors.to_xml }
      end
    end
  end

  # DELETE /tutelle_logos/1
  # DELETE /tutelle_logos/1.xml
  def destroy
    @tutelle_logo = TutelleLogo.find(params[:id])
    @tutelle_logo.destroy

    respond_to do |format|
      format.html {   redirect_to :back  }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tutelle_logos_helper.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
module TutelleLogosHelper
end

app/views/tutelle_logos/edit.html.erb
<h1> Modifier le logo associé à la tutelle <%= @tutelle_logo.tutelle.nom %> </h1>
<div class="lien">
	<%= link_to 'Annuler', edit_tutelle_path(@tutelle_logo.tutelle) %>
</div>
<%= error_messages_for :tutelle_logos %>

<% form_for(:tutelle_logos, :url => tutelle_logo_path, :html => {:method => :put, :multipart => true, :class => "with_photo" }) do |f| %>
	<p>
		<label for="tutelle_logo_logo">Logo associé</label>
		<%= file_column_field 'tutelle_logo', 'logo' %><br />
		<span class="aide">Le logo associé doit être au format Jpg</span>
	</p>
  	<p>
    	<%= submit_tag "Créer" %>
  	</p>
<% end %>
<div class="photo_form">
	<%= image_tag url_for_file_column(@tutelle_logo, "logo") %>
</div>
<div style="clear:both;"></div>

app/views/tutelle_logos/index.html.erb
<h1>Listing tutelle_logos</h1>

<table>
  <tr>
    <th>Tutelle</th>
    <th>Logo</th>
    <th>Created at</th>
    <th>Updated at</th>
  </tr>
  
<% for tutelle_logo in @tutelle_logos %>
  <tr>
    <td><%=h tutelle_logo.tutelle_id %></td>
    <td><%=h tutelle_logo.logo %></td>
    <td><%=h tutelle_logo.created_at %></td>
    <td><%=h tutelle_logo.updated_at %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tutelle_logos/new.html.erb
<h1> Ajouter un logo associé à la tutelle <%= @tutelle_logo.tutelle.nom %> </h1>
<div class="lien">
	<%= link_to 'Annuler', edit_tutelle_path(@tutelle_logo.tutelle) %>
</div>
<%= error_messages_for :tutelle_logos %>

<%= form_for(:tutelle_logos, :url => tutelle_logos_path, :html => {:multipart => true, :class => "with_photo" }) do |f| %>
	<p>
		<label for="tutelle_logo_logo">Logo associé</label>
		<%= file_column_field 'tutelle_logo', 'logo' %><br />
		<span class="aide">Le logo associé doit être au format Jpg</span>
	</p>
  	<p>
    	<%= submit_tag "Créer" %>
  	</p>
<% end %>
<div class="photo_form">
  <%= image_tag 'logo_null.jpg', :alt => "logo"
</div>
<div style="clear:both;"></div>

app/views/tutelle_logos/show.html.erb
<p>
  <b>Tutelle:</b>
  <%=h @tutelle_logo.tutelle_id %>
</p>

<p>
  <b>Logo:</b>
  <%=h @tutelle_logo.logo %>
</p>

<p>
  <b>Created at:</b>
  <%=h @tutelle_logo.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%=h @tutelle_logo.updated_at %>
</p>


<%= link_to 'Edit', edit_tutelle_logo_path(@tutelle_logo) %> |
<%= link_to 'Back', tutelle_logos_path %>