config/routes.rb
OscNew::Application.routes.draw do

  root :to => "contrats#index"
  
  resources :accounts
  
  resources :budgetaire_references do
    member do
      get :ask_delete
    end
  end
    
  resources :contrats do
    member do
      get :ask_delete
      get :show_not_authorized_users
      get :show_not_authorized_groups
      get :reporting
      post :add_user
      post :add_group
      post :delete_user
      post :delete_group
      post :duplicate
    end
    collection do
      get :my_last_search
      get :search
    end
    resources :todolists do
      member do
        post :update_positions
        get :ask_delete
      end
      resources :todoitems do
        member do
          post :undone
          post :done
          post :update_positions
          get :ask_delete
        end
      end
    end
    resources :signatures do
      member do
        get :ask_delete
      end    
    end
    resources :soumissions do
      member do
        get :ask_delete
        get :getpdf
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :refus do
      member do
        get :ask_delete
      end
    end
    resources :notifications do
      member do
        get :ask_delete
      end
      collection do
        get :update_type_contrat
      end
    end
    resources :clotures do
      member do
        get :ask_delete
      end
    end
    resources :echeanciers do
      member do
        get :ask_delete
      end
    end
    resources :contrat_files do
      member do
        get :edit_description
        put :update_description
        get :ask_delete
      end
      collection do
        post :sort_by
      end
    end
    resources :descriptifs do
      member do
        get :ask_delete
      end
    end
  end
  
  resources :contrat_types do
    member do
      get :ask_delete
    end
  end
  resources :departements do
    member do
      get :ask_delete
    end
  end
  resources :departement_subscriptions do
    member do
      post :create
    end
  end
  resources :groups do
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  
  resources :key_words do
    member do
      get :ask_delete
    end
   
    collection do
      post :sort_by
    end
  end
  
  resources :laboratoires do
    member do
      get :ask_delete
    end
  end
  resources :laboratoire_subscriptions do
    member do
      post :create
    end
  end
  resources :lignes do
    collection do
      get :search
      get :search_in_create
      get :my_last_search
      post :toggle_show_justification_data_preferences
    end
    member do
      get :ask_delete
      get :ask_desactivate
      get :bilan
      post :desactivate
      post :activate
    end
    resources :versements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_fonctionnements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_equipements do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_missions do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_salaires do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
      collection do
        post :search_people_from_ose
        post :search_people_from_gef
        get :create_salaires_from_gef
      end
    end
    resources :depense_non_ventilees do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
    resources :depense_communs do
      member do
        get :ask_delete
        post :duplicate
        get :build_migration_form
      end
    end
  end

  resources :memberships

  resources :organisme_gestionnaires do
    member do
      get :ask_delete
    end
    resources :organisme_gestionnaires_tauxes
  end

  resources :projets do
    member do
      get :ask_delete
    end
    collection do 
      get :search_by_name
    end
  end
  resources  :rubrique_comptables do
    member do
      get :ask_delete
    end
  end
  resources :sous_contrats do
    member do
      get :ask_delete
    end
  end
  resources :tutelles do 
    member do
      get :ask_delete
    end
  end
  resources :tutelle_logos
  resources :tutelle_subscriptions do
    member do
      post :create
    end
  end

  resources :users do
    collection do 
      get :search_by_name
    end
    member do
      post :delete_droit
      post :delete_role
      get :ask_delete
    end
    resources :user_images
  end
  

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/depense_communs_controller.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
class DepenseCommunsController < DepensesController
  include UIEnhancements::SubList
  helper :SubList

  sub_list 'DepenseCommunFactures', 'depense_commun' do |new_depense_commun_facture|
  end

  auto_complete_for :depense_commun, :fournisseur

  before_filter :set_lignes_editables, :set_lignes_consultables
  before_filter :is_my_ligne_research_in_session?

  # GET /depense_communs
  # GET /depense_communs.xml
  def index
    setup_order_by :name => 'commun', :default_field => 'date_commande', :default_direction => 'desc'
    setup_depenses_filter
    setup_items_per_page
    setup_depenses_dates
    setup_depenses_facture
    setup_type_montant(@ligne.contrat.come_from_inria?)

    if  @order_by_field == 'budgetaire_reference'
      depenses = DepenseCommun.find_all_by_ligne_id(@ligne.id,
        :include    => :budgetaire_reference,
        :conditions => @filter_condition + @date_condition)

      depenses.sort! { |a,b|
        a.budgetaire_reference.code <=> b.budgetaire_reference.code }

      depenses.reverse! if @order_by_direction != "asc"

      @depense_communs = depenses.paginate(
        :page       => params[:page],
        :per_page   => @items_per_page)

      setup_depenses_totals(depenses, DepenseCommun)

    else
      depenses = @ligne.depense_communs.all(:conditions => @filter_condition + @date_condition)
      @depense_communs = sort_and_paginate_depenses(depenses)
      setup_depenses_totals(depenses, DepenseCommun)
    end

    @colspan_totals = 8 # override default
    respond_to do |format|
      format.html {
        if !@ligne.contrat.is_consultable? current_user
            flash[:error] = ("Vos droits dans l'application ne vous permettent pas d'accéder à la ligne "+@ligne.nom+".").html_safe()
            redirect_to lignes_path
        end
      }
      format.js {
        render :partial => 'list.html.erb'
      }
      format.xml  { render :xml => @depense_communs }
      format.csv { render :text => export_csv(depenses,'commun') }
    end
  end

  # GET /depense_communs/new
  # GET /depense_communs/new.xml
  def new
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.new
    @budgetaire_references = BudgetaireReference.find(:all, :order => :code).collect {|p| [ p.code+" "+p.intitule, p.id ] }

    if !@ligne.contrat.is_budget_editable? current_user
      flash[:error] = ("Vos droits dans l'application ne vous permettent pas de créer de dépense en commun pour la ligne "+@ligne.nom+".").html_safe()
      redirect_to ligne_depense_communs_path(@ligne)
    end
  end

  # POST /depense_communs
  # POST /depense_communs.xml
  def create
    params[:depense_commun] = clean_date_params(params[:depense_commun])
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.new(params[:depense_commun])
    @budgetaire_references = BudgetaireReference.find(:all, :order => :code).collect {|p| [ p.code+" "+p.intitule, p.id ] }
    @depense_commun.ligne = @ligne

    success = true
    success &&= initialize_depense_commun_factures
    success &&= @depense_commun.save

    # Pour une mise à jour correcte de date_min et date_max
    @depense_commun.update_dates_min_max
    @depense_commun.save
    
    respond_to do |format|
      if success
        flash[:notice] = ('La dépense en commun a bien été crée.').html_safe()
        format.html { redirect_to ligne_depense_commun_path(@ligne, @depense_commun) }
      else
        prepare_depense_commun_factures
        format.html { render :action => "new" }
      end
    end
  end

  # GET /depense_communs/1/edit
  def edit
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.find(params[:id])
    @budgetaire_references = BudgetaireReference.find(:all, :order => :code).collect {|p| [ p.code+" "+p.intitule, p.id ] }

    if !@ligne.contrat.is_budget_editable? current_user
      flash[:error] = ("Vos droits dans l'application ne vous permettent pas d'éditer les dépenses en commun de la ligne "+@ligne.nom+".").html_safe()
      redirect_to ligne_depense_commun_path(@ligne, @depense_commun)
    end
  end

  # PUT /depense_communs/1
  # PUT /depense_communs/1.xml
  def update
    params[:depense_commun] = clean_date_params(params[:depense_commun])
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.find(params[:id])
    @budgetaire_references = BudgetaireReference.find(:all, :order => :code).collect {|p| [ p.code+" "+p.intitule, p.id ] }

    @depense_commun.update_attributes(params[:depense_commun])

    success = true
    success &&= initialize_depense_commun_factures
    success &&= @depense_commun.save

    respond_to do |format|
      @ligne =  @depense_commun.ligne
      if success
        if (params[:ajuster_montant])
          @depense_commun.montant_engage = @depense_commun.montant_factures('ttc')
        end
        @depense_commun.update_dates_min_max
        @depense_commun.verif = false
        @depense_commun.save
        flash[:notice] = ('La dépense en commun a bien été mise à jour.').html_safe()
        format.html { redirect_to ligne_depense_commun_path(@ligne, @depense_commun) }
      else
        prepare_depense_commun_factures
        format.html { render :action => "edit" }
      end
    end
  end

  # POST /depense_communs/1/duplicate
  def duplicate
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.find(params[:id])
    @new_depense_commun = @depense_commun.dup
    @new_depense_commun.reference=""
    @new_depense_commun.commande_solde= false
    @new_depense_commun.verif = 0
    if !@ligne.contrat.is_budget_editable? current_user
      flash[:error] = ("Vos droits dans l'application ne vous permettent pas de créer de dépense en commun sur la ligne "+@ligne.nom+".").html_safe()
      redirect_to ligne_depense_commun_path(@ligne)
    end
    @new_depense_commun.save
    flash[:notice] = ('La dépense a bien été dupliquée.').html_safe()
    respond_to do |format|
      format.html { redirect_to edit_ligne_depense_commun_path(@ligne, @new_depense_commun) }
    end
  end

  def show
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.find(params[:id])

    # test si la reference existe dans une autre depense, pour message d'avertissement
    if !@depense_commun.reference.blank? && search_all_exact_references(@depense_commun.reference).size > 1
      @ref_exist = true
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @depense_commun }
    end
  end

  def build_migration_form
    @depense_commun = DepenseCommun.find(params[:id])
    dotation_contrat_type_ids = ContratType.find_all_dotation_type_id
    req = "Select lignes.id,lignes.nom from lignes 
                         inner join sous_contrats on sous_contrats.id = lignes.sous_contrat_id
                         inner join contrats on contrats.id = sous_contrats.contrat_id
                         inner join notifications on notifications.contrat_id = contrats.id
                         where notifications.contrat_type_id IN (?) and lignes.id IN (?) ORDER BY nom" 
    @available_lignes = Ligne.find_by_sql([req,dotation_contrat_type_ids, @ids_lignes_editables]).collect { |p| [ p.nom, p.id ] }
    respond_to do |format|
      format.js {
        render :partial => "migration_form"
      }
    end
  end
  
  def ask_delete
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # DELETE /depense_communs/1
  # DELETE /depense_communs/1.xml
  def destroy
    @ligne = Ligne.find(params[:ligne_id])
    @depense_commun = DepenseCommun.find(params[:id])
    @depense_commun.destroy

    respond_to do |format|
      format.html { redirect_to(ligne_depense_communs_path(@ligne)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/depense_communs_helper.rb
#!/bin/env ruby
# encoding: utf-8
#07-2013 Migration in Ruby On Rails  3.2 by Benjamin Ninassi
module DepenseCommunsHelper
end

app/views/depense_communs/_ask_delete_depense_commun_facture.html.erb
<div class="content">
	<p>
		Etes-vous certain de vouloir supprimer cette facture ?
	</p>
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= sub_list_accept_to_remove_link("depense_commun_facture") %>
 	<div style="clear:both;"></div>
</div>

app/views/depense_communs/_depense_commun_facture.html.erb
<% @depense_commun_facture = depense_commun_facture %>

<div id="<%= "depense_commun_facture_#{depense_commun_facture.id}" %>">
  
  <div class="form-box child">
    <h3>Facture</h3>
    <div class="remove_facture">
       <%= sub_list_remove_link depense_commun_facture, 'DepenseCommunFacture' %>
    </div>
    
    <div class="clearfix">
      <div class="col-1-of-2">      
        <p class="inline ">
          <label class="required">Date de facture</label><br />
            <%= unobtrusive_date_picker 'depense_commun_facture[]',
                                        :date,
                                        :include_blank => true,
                                        :use_month_numbers => true,
                                        :class => 'no-transparency',
                                        :id => "#{@depense_commun_facture.id}" %>
        </p>

         <p class="inline ">
          <label>Date de service fait  (millésime)</label><br />
            <%= unobtrusive_date_picker 'depense_commun_facture[]',
                                        :millesime,
                                        :include_blank => true,
                                        :use_month_numbers => true,
                                        :class => 'no-transparency',
                                        :id => "#{@depense_commun_facture.id}" %>
        </p>

       <p>
          <label>N° de facture</label><br />
          <%= text_field 'depense_commun_facture[]', 'numero_facture' %>
        </p>
    
        <p >
          <label>Commentaire</label><br />
          <%= text_area 'depense_commun_facture[]', :commentaire %>
        </p>
    
        <p >
          <label>N° de mandat</label><br />
          <%= text_field 'depense_commun_facture[]', :numero_mandat %>
        </p>
    
        <p class="inline ">
          <label>Date de mandatement</label><br />
            <%= unobtrusive_date_picker 'depense_commun_facture[]',
                                        :date_mandatement,
                                        :include_blank => true,
                                        :use_month_numbers => true,
                                        :class => 'no-transparency',
                                        :id => "#{@depense_commun_facture.id}" %>
        </p>
      </div>

      <div class="col-2-of-2">
    
        <p >
          <label class="required">Montant Payé (HT)</label><br />
          <%= text_field 'depense_commun_facture[]', :cout_ht %>
        </p>
    
        <p >
          <label class="required">Taux de TVA</label><br />
          <%= select 'depense_commun_facture[]',
                     :taux_tva,  ["0","2.1", "5.5", "19.6"],
                     {} %>
        </p>
    
        <p >
          <label>Justifiable</label><br />
          <%= select 'depense_commun_facture[]',
                     :justifiable, ["","Possible","Impossible","Utilisée","Refusée"],
                     {} %>
        </p>
    
        <p >
          <label>Rubrique Comptable</label><br />
          <%= select 'depense_commun_facture[]',
                     :rubrique_comptable_id, 
                     options_for_rubrique_comptables(RubriqueComptable.find(:all, :order => 'numero_rubrique')),
                     {} %>
        </p>
         <p>
          <label>Compte Budgétaire</label><br />
          <%= text_field 'depense_commun_facture[]', :compte_budgetaire %>
        </p>
        <p>
          <label>Code Analytique</label><br />
          <%= text_field 'depense_commun_facture[]', :code_analytique %>
        </p>
      </div>
    </div>
  </div>
</div>

<%- if controller.action_name.to_s == "add_depense_commun_facture" -%>
  <script type="text/javascript">
    datePickerController.create();
  </script>
<%- end -%>

app/views/depense_communs/_list_show_factures.html.erb
<tr class="factures">
  <th></th>
  <th></th>
  <th class="first">N° de facture</th>
  <th>Date</th>
  <th colspan="3">N° de mandat et date</th>
  <th colspan="2">Justifiable </th>
  <th>Rubrique</th>
  <th class="money">Coût Projet</th>
  <%- if @ligne.contrat.is_budget_editable? current_user -%>
  <th class="actions">&nbsp;</th>
  <%- end -%>
</tr>
<%-
  case @type_montant.to_s
	when "htr" then cout_facture = "cout_ht"
	when "ht" then cout_facture = "cout_ht"
	when "ttc" then cout_facture = "cout_ttc"
  end
-%>
<% for facture in @depense_commun.depense_commun_factures %>
     <tr class="factures">
      <td></td>
      <%
      verrou_class = 'no-verrou'
      %>
      <td class="<%= verrou_class %> "></td>
      <td class="first"><%= facture.numero_facture %></td>
			<td><%= french_small_date facture.date %>
      <% if !facture.millesime.blank? %>
      <br/>(<%= facture.millesime.year %>)
      <% end %>
      </td>
      <td><%= facture.numero_mandat %></td>
      <td colspan="2">
        <% if !facture.date_mandatement.blank? %>
          <%= french_small_date facture.date_mandatement %>
        <%end%>
      </td>
      <td colspan="2"><%=  facture.justifiable %></td>
      <td><%= facture.rubrique_comptable.small_intitule %></td>
      <td class="money"><%= my_number_to_currency facture.send(cout_facture) %></td>
      <%- if @ligne.contrat.is_budget_editable? current_user -%>
      <td class="actions_depenses">&nbsp;</td>
      <%- end -%>
    </tr>
<% end %>
<tr class="sep"><td colspan='9'></td></tr>

app/views/depense_communs/_migration_form.html.erb
<h3>Modification de la ligne associée à la dépense du commun</h3>
<p>
  <label class="required" for="depense_commun_ligne_id">Ligne associée</label><br />
  <%= select( "depense_commun", "ligne_id", @available_lignes) %>
</p>

app/views/depense_communs/ask_delete.html.erb
<div class="content">
	<p>
	Etes-vous certain de vouloir supprimer cette dépense du commun ?<br />
	</p>
	<%= link_to_close_redbox "Non", :class => 'annuler' %>
	<%= link_to "Oui", ligne_depense_commun_path(@ligne, @depense_commun), :method => :delete %>
	<div style="clear:both;"></div>
</div>

app/views/depense_communs/index.html.erb
<%- content_for :right do -%>
	<%- if @ligne.contrat.is_budget_editable? current_user -%>
		<%= link_to 'Ajouter une dépense du commun', new_ligne_depense_commun_path(@ligne), {:class => "add-depense-commun"} %>
	<%- end -%>
	<%= render :partial => 'lignes/selection_temporelle' %>
<%- end -%>

<% content_for :options do %>
	<%= render :partial => 'lignes/depenses_index_options' %>
<% end %>

<div id="to-update">
	<%= render :partial => 'list' %>
</div>

<script type="text/javascript">
	new App.Budget.ItemsParPageSlider(<%= @items_per_page.to_s %>);
	new App.Budget.ListView();
	function updateResult(page_number){
    new Ajax.Updater('to-update', '/lignes/<%= @ligne.id.to_s %>/depense_communs?page='+page_number,
                    {asynchronous:true, evalScripts:true, method:'get'});
  }
</script>

app/views/depense_communs/new.html.erb
<%= error_messages_nested_resources_for @depense_commun %>

<%= form_for([@ligne, @depense_commun]) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f} %>
  <div class="form-box submit">
    <%= f.submit "Créer la dépense en commun" %> ou <%= link_to 'Annuler', ligne_depense_communs_path(@ligne) %>
  </div>
<% end %>

app/views/depense_communs/show.html.erb
<% content_for :right do %>
  <%- if @ligne.contrat.is_budget_editable? current_user -%>
    <%= link_to 'Ajouter une dépense du commun', new_ligne_depense_commun_path(@ligne), {:class => "add-depense-commun"} %>
    <%= link_to 'Dupliquer cette dépense',  duplicate_ligne_depense_commun_path(@ligne, @depense_commun),  {:method => :post, :class => "duplicate-depense"} %>
  <%- end -%>
<%- end -%>

<%- if @ref_exist -%>
  <div id="errorExplanation" class="errorExplanation"><h2>Attention, la référence a déjà été saisie pour une autre dépense. </h2></div>
<%- end -%>

<div class="box parent">
  <h2>Demande d'achat</h2>
  <div class="clearfix">
    <div class="large-col">
      <div class='line clearfix'>
        <span class="attribute">Date de demande d'achat</span>
        <span class="value"><%= french_date @depense_commun.date_commande %></span>
      </div>
      <div class='line clearfix'>
        <span class="attribute">Référence</span>
        <span class="value"><%=  @depense_commun.reference %></span>
      </div>
      <div class='line clearfix'>
        <span class="attribute">Fournisseur</span>
        <span class="value"><%=h @depense_commun.fournisseur %></span>
      </div>
      <div class='line clearfix'>
        <span class="attribute">Intitulé</span>
        <div class="value"><%= simple_format @depense_commun.intitule %></div>
      </div>
      <div class='line clearfix'>
        <span class="attribute">Destination budgétaire</span>
        <span class="value"><%= @depense_commun.budgetaire_reference.code %> <%= @depense_commun.budgetaire_reference.intitule%> </span>
      </div>
	    <div class='line last clearfix'>
        <span class="attribute">Commentaire</span>
        <div class="value"><%= simple_format @depense_commun.commentaire %></div>
      </div>
      <div class="line clearfix">
        <span class="attribute">Compte Budgétaire</span>
        <div class="value"><%=simple_format @depense_commun.compte_budgetaire %></div>
      </div>
      <div class="line last clearfix">
        <span class="attribute">Code Analytique</span>
        <div class="value"><%=simple_format @depense_commun.code_analytique %></div>
      </div>
      <div class="line last clearfix">
        <span class="attribute">Code Projet</span>
        <div class="value"><%=simple_format @depense_commun.code_projet %></div>
      </div>
    </div>
    <div class="small-col">
      <div class='line last clearfix'>
        <span class="attribute">Montant engagé</span>
        <span class="value <%= "soldee" if @depense_commun.commande_solde %>">
          <strong><%= my_number_to_currency @depense_commun.montant_engage %></strong>
        </span>
      </div>
    </div>
  </div>
</div>

<div id="justification-data" <%= 'style="display:none;"'.html_safe() if @user_preferences_show_justifacation_data == 'no' %>>
  <div class="box sub-parent">
    <h2>Justification</h2>
    <div class="clearfix">
      <div class="large-col">
        <div class='line clearfix'>
          <span class="attribute">Nom de la tâche imputée</span>
          <span class="value"><%= @depense_commun.tache %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Commande éligible ?</span>
          <span class="value"><% if @depense_commun.eligible %>Oui<% else %>Non<% end %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Prestation de service ?</span>
          <span class="value"><% if @depense_commun.prestation_service %>Oui<% else %>Non<% end %></span>
        </div>
        <div class='line last clearfix'>
          <span class="attribute">Type d'activité</span>
          <span class="value"><%= @depense_commun.type_activite %></span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="sub-parent-toggle-container">
  <a href="#" id="toggle-justification">
    <%- if @user_preferences_show_justifacation_data == 'no' -%>
      Afficher les données de justification
    <%- else -%>
      Masquer les données de justification
    <%- end -%>
  </a>
</div>


<% i = 1 %>
<% for facture in @depense_commun.depense_commun_factures %>
  <%- if i == @depense_commun.depense_commun_factures.size -%>
    <div class="child-container last">
  <%- else -%>
    <div class="child-container default">
  <%- end -%>
  <div class="box child">
    <h2>Facture</h2>
    <div class="clearfix">
      <div class="large-col">
        <div class='line clearfix'>
          <span class="attribute">Date de la facture</span>
          <span class="value"><%= french_date facture.date %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Date de service fait (millésime)</span>
          <span class="value"><%= french_date facture.millesime unless facture.millesime.nil? %></span>
      </div>
      <div class='line clearfix'>
          <span class="attribute">N° de la facture</span>
          <span class="value"><%= facture.numero_facture %> <%= facture.id %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Rubrique comptable</span>
          <span class="value"><%= facture.rubrique_comptable.intitule %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Commentaire</span>
          <div class="value"><%= simple_format facture.commentaire %></div>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Justification</span>
          <span class="value"><%= facture.justifiable %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">N° de mandat</span>
          <span class="value"><%= facture.numero_mandat %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Date de mandatement</span>
          <span class="value"><%= french_date facture.date_mandatement if !facture.date_mandatement.blank? %></span>
        </div>
        <div class="line clearfix">
          <span class="attribute">Compte Budgétaire</span>
          <div class="value"><%=simple_format facture.compte_budgetaire %></div>
        </div>
        <div class="line last clearfix">
          <span class="attribute">Code Analytique</span>
          <div class="value"><%=simple_format facture.code_analytique %></div>
        </div>
      </div>
      <div class="small-col">
        <div class='line clearfix'>
          <span class="attribute">Montant Payé (HT)</span>
          <span class="value"><%= my_number_to_currency facture.cout_ht %></span>
        </div>
        <div class='line clearfix'>
          <span class="attribute">Taux de TVA</span>
          <span class="value"><%= facture.taux_tva %>%
        </div>
        <div class='line clearfix'>
          <span class="attribute">Montant Payé (TTC)</span>
          <span class="value"><%= my_number_to_currency facture.cout_ttc %></span>
        </div>
      </div>
    </div>
  </div>
</div>
<% i += 1 %>
<% end %>

<div class="box dashboard">
  <div class="clearfix">
    <div class="large-col">
      <%- if @depense_commun.commande_solde -%>
        La commande est soldée.
      <%- else -%>
        La commande n'est pas soldée.
      <%- end -%>
    </div>
    <div class="small-col">
      <div class='line clearfix'>
        <span class="attribute">Coût Total HT</span>
        <span class="value">
          <%= my_number_to_currency @depense_commun.montant_factures('ht') %>
        </span>
      </div>
      <div class='line clearfix'>
        <span class="attribute">Coût Total TTC</span>
        <span class="value">
          <%= my_number_to_currency @depense_commun.montant_factures('ttc') %>
        </span>
      </div>
    </div>
  </div>
</div>

<div id="content_footer">
  <div class="left">
    Création le <%= french_datetime @depense_commun.created_at %> par <%= print_user_infos @depense_commun.created_by %>
    <% if @depense_commun.created_at != @depense_commun.updated_at %>
    <br />
    Dernière modification le <%= french_datetime @depense_commun.updated_at %> par <%= print_user_infos @depense_commun.updated_by %>
    <% end %>
  </div>
  <div class="right">
    <%- if (@ligne.contrat.is_budget_editable? current_user) -%>
    <%= link_to_remote_redbox "Supprimer la dépense",
        { :url => ask_delete_ligne_depense_commun_path(@ligne, @depense_commun), :method => :get},
        { :class => "destroy",
          :title => "Supprimer la dépense" }  %>
    <%- end -%>
  </div>
  <div style="clear:both;"></div>
</div>

<script type="text/javascript">
  new App.Budget.ToggleJustificationData();
</script>